name: Enforce PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist_edited:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for checklist completion
        uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.pull_request.body;
            const checkboxes = body.match(/- \[[ xX]\]/g);
            const incomplete = body.match(/- \[ \]/g);
            if (checkboxes && incomplete && incomplete.length > 0) {
              core.setFailed(`Checklist incomplete: ${incomplete.length} item(s) left.`);
            } else {
              console.log("Checklist fully complete or not found. Skipping failure.");
            }
